image: "registry.git.rwth-aachen.de/georgar/kasm:latest"

cache:
  paths:
    - target/

build-linux64:
  stage: build
  script:
    - cargo build -r --target=x86_64-unknown-linux-gnu
  artifacts:
    name: kasm.linux64-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expose_as: "kasm-linux64"
    paths:
      - target/x86_64-unknown-linux-gnu/release/kasm

build-win64:
  stage: build
  script:
    - cargo build -r --target=x86_64-pc-windows-gnu
  artifacts:
    name: kasm.win64-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expose_as: "kasm-win64"
    paths:
      - target/x86_64-pc-windows-gnu/release/kasm.exe
